# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dht_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dht_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ht_service.proto\x12\x03\x64ht\"\x1c\n\rLookupRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"*\n\x0eLookupResponse\x12\x18\n\x10responsible_node\x18\x01 \x01(\t2?\n\nDHTService\x12\x31\n\x06Lookup\x12\x12.dht.LookupRequest\x1a\x13.dht.LookupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dht_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=26
  _globals['_LOOKUPREQUEST']._serialized_end=54
  _globals['_LOOKUPRESPONSE']._serialized_start=56
  _globals['_LOOKUPRESPONSE']._serialized_end=98
  _globals['_DHTSERVICE']._serialized_start=100
  _globals['_DHTSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
