version: '3.8'

services:
  portmapper:
    build: .
    container_name: portmapper
    ports:
      - "5000:5000"
    command: ["python", "portmapper.py"]

  node1:
    build: .
    container_name: node1
    ports:
      - "5001:5001"
    environment:
      - NODE_NAME=node1
      - PORT=5001
      - BOOTSTRAP_NODE=http://portmapper:5000
    depends_on:
      - portmapper
    command: ["python", "peer_node.py"]

  node2:
    build: .
    container_name: node2
    ports:
      - "5002:5002"
    environment:
      - NODE_NAME=node2
      - PORT=5002
      - BOOTSTRAP_NODE=http://node1:5001
    depends_on:
      - node1
    command: ["python", "peer_node.py"]

  node3:
    build: .
    container_name: node3
    ports:
      - "5003:5003"
    environment:
      - NODE_NAME=node3
      - PORT=5003
      - BOOTSTRAP_NODE=http://node2:5002
    depends_on:
      - node2
    command: ["python", "peer_node.py"]
